name: Feature Request
description: Request a new feature or enhancement for the Galaxy tips system
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible about your idea.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A brief title for your feature request
      placeholder: "e.g., 'Add dark mode support for tips display'"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Describe the current limitation or problem you're experiencing"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        How would you like this feature to work?
        What should the user experience be like?
    validations:
      required: true
