name: Tip Request
description: Request a new Galaxy tip to be added
title: "[Tip request] "
labels: ["tip request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new Galaxy tip! Your suggestion will help other users learn about Galaxy features.

  - type: checkboxes
    id: tip-purpose
    attributes:
      label: Does this tip help users to operate Galaxy Australia better?
      description: Tips are intended to help users to navigate the service. They shouldn't be used to promote related events or services, as this can reduce user engagement.
      options:
        - label: Yes, this tip helps users operate Galaxy Australia better
          required: true

  - type: input
    id: tip-title
    attributes:
      label: Tip Title
      description: A catchy title for your tip
      placeholder: "e.g., 'Using keyboard shortcuts to navigate Galaxy'"
    validations:
      required: true

  - type: textarea
    id: tip-content
    attributes:
      label: Tip Content
      description: Describe the tip content in detail
      placeholder: |
        Explain the Galaxy feature, workflow, or best practice you'd like to share.
        If applicable, include step-by-step instructions and images or video links.
    validations:
      required: true
